export const location1 = [
  "Auto Fair",
  "Autosalon",
  "Bahama Mamas Bar",
  "Capitol",
  "Cayo Perico Island",
  "Chumash",
  "Church",
  "Del Perro Pier",
  "Del Perro Beach",
  "Diamond Resort Bar (Casino Restaurant)",
  "FIB",
  "Fire Station",
  "Hospital",
  "Hotel",
  "Lifeinvader",
  "Mirror Park",
  "Paleto Bay",
  "Postal",
  "Raton Canyon",
  "Richman",
  "Rockford Hills",
  "SAHP",
  "Sandy Shores",
  "Stadium",
  "Stock Exchange",
  "Tequi-la-la Bar",
  "Vanilla Unicorn Bar",
  "Vinewood Hills",
];

export const location2 = [
  "airport",
  "beach",
  "beach market",
  "ghetto",
  "post office",
  "train station",
  "the city",
];

export const apartmentLocations = [
  "Eclipse Towers",
  "Tinsel Towers",
  "Del Perro Heights",
  "Richards Majestic",
  "Tinkle Building",
  "3 Alta Street",
  "Celltowa Building",
  "near the beach market",
];

export const autoNames = [
  "9F",
  "9F Cabrio",
  "Adder",
  "Alpha",
  "Annis ZR-350",
  "Annis 350Z",
  "Annis Silvia (S15)",
  "Annis Skyline GT-R (R34)",
  "Annis GT-R I",
  "Annis RX-7 (FD)",
  "Annis WRX 2004",
  "Apocalypse Impaler",
  "Apocalypse Imperator",
  "Apocalypse Issi",
  "Apocalypse Slamvan",
  "Ardent",
  "Asbo",
  "Asea",
  "Asterope",
  "Autarch",
  "Albany Escalade",
  "Akuma",
  "Apocalypse Deathbike",
  "Avarus",
  "Baller",
  "Baller LE LWB",
  "Baller SG",
  "Banshee",
  "Banshee 900R",
  "Beater Emperor",
  "Beater Mariachi Tornado",
  "Beater Surfer",
  "Beater Tornado",
  "Benefactor-AMG C63 (W205)",
  "Benefactor-AMG C63 Coupe (W205)",
  "Benefactor-AMG G63 (G770)",
  "Benefactor-AMG GT Black Series",
  "Benefactor-AMG S63 (W222)",
  "Benefactor-Benz 600SEL (W140)",
  "Benefactor-Benz E420 (W210)",
  "Benefactor-Benz Vito (V447)",
  "Benefactor-Maybach Pullman",
  "Bestia GTS",
  "BF Injection",
  "Bison",
  "Blade",
  "Blista",
  "Blista Kanjo",
  "Bodhi",
  "Brawler",
  "Bravado Charger 1969",
  "Bravado Ram 1500",
  "Bravado Viper 2008",
  "Brioso R/A",
  "Buccaneer",
  "Buffalo",
  "Bullet",
  "Benefactor-AMG GT",
  "Benefactor-AMG SL65 (R230)",
  "Burgerfahrzeug Golf GTI Vision",
  "Bagger",
  "Bati 801",
  "Bati 801RR",
  "BF-400",
  "Blazer",
  "Blazer Lifeguard",
  "BMX",
  "Calico GTF",
  "Caracara 4x4",
  "Carbonizzare",
  "Casco",
  "Cavalcade",
  "Cheburek",
  "Cheetah",
  "Cheetah Classic",
  "Chino",
  "Clique",
  "Coil Cybertruck",
  "Coil Model S",
  "Coil Model X",
  "Coil Roadster",
  "Cognoscenti",
  "Cognoscenti 55",
  "Cognoscenti Cabrio",
  "Comet",
  "Comet S2",
  "Comet SR",
  "Contender",
  "Coquette",
  "Coquette Blackfin",
  "Coquette D10",
  "Couquette Classic",
  "Cyclone",
  "Cypher",
  "Carbon RS",
  "Chimera",
  "Cliffhanger",
  "Cruiser",
  "Declasse Corvette C7",
  "Declasse Tahoe",
  "Deveste Eight",
  "Deviant",
  "Dilettante",
  "Dinka RT-3000",
  "Dinka NSX 2017",
  "Dominator",
  "Dominator ASP",
  "Dominator GTT",
  "Dominator GTX",
  "Dominator PiBwasser",
  "Drift Yosemite",
  "Dubsta",
  "Dubsta 6x6",
  "Dubsta SG",
  "Dukes",
  "Declasse Camaro 2020",
  "Daemon",
  "Defiler",
  "Diabolus",
  "Diabolus Custom",
  "Double-T",
  "Elegy Retro Custom",
  "Elegy RH8",
  "Ellie",
  "Emperor",
  "Emperor LX-570",
  "Emperor RCF",
  "Entity XF",
  "Enus Cullinan",
  "Enus Phantom",
  "Enus Continental GT",
  "ETR-1",
  "Euros",
  "Exemplar",
  "Enduro",
  "Esskey",
  "F620",
  "Faction",
  "Felon",
  "Felon GT",
  "Feltzer",
  "Flash GT",
  "FMJ",
  "FQ 2",
  "Fugitive",
  "Furore GT",
  "Fusilade",
  "Futo",
  "Futo GTX",
  "Future Shock Issi",
  "Faggio",
  "FCR 1000",
  "FCR 1000 Custom",
  "Future Shock Deathbike",
  "Gallivanter Defender Halloween Edition",
  "Gallivanter Defender Christmas Edition",
  "Gauntlet",
  "Gauntlet Classic",
  "Gauntlet Hellfire",
  "Gauntlet Redwood",
  "GB200",
  "Glendale",
  "GP-1",
  "Granger",
  "Growler",
  "Grotti Italia (F458)",
  "GT 500",
  "Gargoyle",
  "Hermes",
  "Hotknife",
  "Huntley S",
  "Hakuchou",
  "Hakuchou Drag",
  "Hexer",
  "Imorgon",
  "Impaler",
  "Infernus",
  "Infernus Classic",
  "Ingot",
  "Issi",
  "Itali GTB",
  "Itali GTB Custom",
  "Itali GTO",
  "Innovation",
  "Jackal",
  "JB 700",
  "Jester",
  "Jester (Racecar)",
  "Jester Classic",
  "Jester RR",
  "Journey",
  "Jugular",
  "Kamacho",
  "Khamelion",
  "Komoda",
  "Krieger",
  "Karin Land Cruiser 200",
  "Karin Mark 2",
  "Karin Supra A80",
  "Karin Tundra 2021",
  "Lampadati Giulia GTA",
  "Landstalker",
  "Lynx",
  "Lectro",
  "Mamba",
  "Massacro",
  "Monroe",
  "Moonbeam",
  "Manchez",
  "Nebula Turbo",
  "Neon",
  "Nero",
  "Nero Custom",
  "Nightshade",
  "Novak",
  "Nemesis",
  "Nightblade",
  "Oracle",
  "Osiris",
  "Obey A8",
  "Obey R8",
  "Obey RS6",
  "Obey RS7",
  "Ocelot Victor",
  "Ocelot F-Type R",
  "Obey A6",
  "Obey Q8",
  "Ocelot Victor",
  "Ocelot Vanquish Zagto SB",
  "Panto",
  "Paragon R",
  "Pariah",
  "Patriot",
  "Patriot Stretch",
  "Pegassi Huayra BC",
  "Pegassi Performante (LP640)",
  "Penetrator",
  "Penumbra",
  "Peyote Gasser",
  "Pfister 811",
  "Pfister Panamera",
  "Pfister Taycan",
  "Pfister 918 Spyder",
  "Pheonix",
  "Picador",
  "Prairie",
  "Premier",
  "Previon",
  "Progen 675 LT",
  "PCJ-600",
  "Raiden",
  "Rancher XL",
  "Rapid GT",
  "Raptor",
  "Rat-Loader",
  "Rat-Truck",
  "RE-7B",
  "Reaper",
  "Rebel",
  "Rebla GTS",
  "Regina",
  "Remus",
  "Revolter",
  "Rhapsody",
  "Riata",
  "Rocoto",
  "Ruiner",
  "Rumpo",
  "Ruston",
  "Rusty Rebel",
  "Rat Bike",
  "Ruffian",
  "Sabre Turbo",
  "Sandking SWB",
  "Sandking XL",
  "SC-1",
  "Schafter",
  "Schafter LWB",
  "Schafter LWB (Armored)",
  "Schafter V12",
  "Schlagen GT",
  "Schwarzer",
  "Seminole",
  "Sentinel Classic",
  "Sentinel XS",
  "Serrano",
  "Seven-70",
  "Shelby GT500",
  "Slam Van",
  "Slamvan Custom",
  "Specter",
  "Stafford",
  "Stallion",
  "Stinger",
  "Stinger GT",
  "Stirling GT",
  "Streiter",
  "Stretch",
  "Sultan",
  "Sultan Classic",
  "Sultan RS",
  "Sultan RS Classic",
  "Super Diamond",
  "Surano",
  "Surge",
  "Swinger",
  "Sanchez",
  "Sanctus",
  "Shotaro",
  "Sovereign",
  "Street Blazer",
  "Stryder",
  "T-20",
  "Tailgater",
  "Tailgater S",
  "Taipan",
  "Tampa",
  "Tempesta",
  "Tezeract",
  "Thrax",
  "Tigon",
  "Torero",
  "Toros",
  "Tropos Rallye",
  "Tulip",
  "Turismo Classic",
  "Turismo R",
  "Truffade Chiron",
  "Tyrant",
  "Tyrus",
  "Thrust",
  "Tri-Cycles Race Bike",
  "Ubermacht 760 (LI)",
  "Ubermacht I8",
  "Ubermacht M3 (G80)",
  "Ubermacht M3 (E46)",
  "Ubermacht M5 (E34)",
  "Ubermacht M5 (E60)",
  "Ubermacht M8 (F91)",
  "Ubermacht X5 (E70)",
  "Ubermacht X5 (G05)",
  "Ubermacht X6-M (E71)",
  "Ubermacht X7 (G07)",
  "V-STR",
  "Vacca",
  "Vagner",
  "Vamos",
  "Vectre",
  "Velierer",
  "Vigero",
  "Virgo",
  "Virgo Classic",
  "Viseris",
  "Visione",
  "Voltic",
  "Voodoo",
  "Voodoo Custom",
  "Vader",
  "Vindicator",
  "Vortex",
  "Warrener",
  "Warrener HKR",
  "Washington",
  "Windsor",
  "Windsor Drop",
  "Whippet Race Bike",
  "Wolfsbane",
  "X80 Proto",
  "XA-21",
  "XLS",
  "XLS (Armored)",
  "Yosemite",
  "Yosemite Rancher",
  "Z-Type",
  "Zentorno",
  "Zion",
  "Zion Cabrio",
  "Zion Classic",
  "Zorrusso",
  "Zombie Chopper",
  "Dinghy",
  "Dinghy (2-Seater)",
  "Dinghy (Yacht)",
  "Jetmax",
  "Marquis",
  "SeaShark",
  "Speeder",
  "Squalo",
  "Suntrap",
  "Toro",
  "Tropic",
  "Alpha-Z1",
  "Cuban 800",
  "Dodo",
  "Duster",
  "Howard NX-25",
  "Luxor",
  "Luxor Deluxe",
  "Malard",
  "Mammatus",
  "Microlight",
  "Nimbus",
  "P-45 Nokota",
  "V-65 Molotok",
  "Velum",
  "Buzzard",
  "Frogger",
  "Maverick",
  "Sparrow",
  "SuperVolito Carbon",
  "Swift Deluxe",
  "Volatus",
  "Monowheel",
];
