export const location1 = [
  "Auto Fair",
  "Bahama Mamas Bar",
  "Capitol",
  "Cayo Perico Island",
  "Chumash",
  "Church",
  "Del Perro Beach",
  "Del Perro Pier",
  "Diamond Resort Bar (Casino Restaurant)",
  "FIB",
  "Fire Station",
  "Hospital",
  "Hotel",
  "Hotel Spa Bar",
  "Lifeinvader",
  "Mirror Park",
  "Pacific Bluffs Country Club",
  "Paleto Bay",
  "Postal",
  "Raton Canyon",
  "Richman",
  "Rockford Hills",
  "SAHP",
  "Sandy Shores",
  "School",
  "Stadium",
  "Stock Exchange",
  "Tequi-la-la Bar",
  "Vanilla Unicorn Bar",
  "Vinewood Hills",
];

export const location2 = [
  "airport",
  "autosalon",
  "beach",
  "beach market",
  "ghetto",
  "post office",
  "the city",
  "train station",
  "yacht",
];

export const apartmentLocations = [
  "3 Alta Street",
  "Celltowa Building",
  "Del Perro Heights",
  "Eclipse Towers",
  "near the beach market",
  "Richards Majestic",
  "Tinkle Building",
  "Tinsel Towers",
];

export const autoNames = [
  "9F",
  "9F Cabrio",
  "Adder",
  "Alpha",
  "Annis ZR-350",
  "Annis 350Z",
  "Annis Silvia (S15)",
  "Annis Skyline GT-R (R34)",
  "Annis GT-R I",
  "Annis RX-7 (FD)",
  "Annis WRX 2004",
  "Apocalypse Impaler",
  "Apocalypse Imperator",
  "Apocalypse Issi",
  "Apocalypse Slamvan",
  "Ardent",
  "Asbo",
  "Asea",
  "Asterope",
  "Autarch",
  "Albany Escalade",
  "Akuma",
  "Apocalypse Deathbike",
  "Avarus",
  "Baller",
  "Baller LE LWB",
  "Baller SG",
  "Banshee",
  "Banshee 900R",
  "Beater Emperor",
  "Beater Mariachi Tornado",
  "Beater Surfer",
  "Beater Tornado",
  "Benefactor-MG C63 (W205)",
  "Benefactor-MG C63 Coupe (W205)",
  "Benefactor-MG G63 (G770)",
  "Benefactor-MG GT Black Series",
  "Benefactor-MG S63 (W222)",
  "Benefactor-Benz 600SEL (W140)",
  "Benefactor-Benz E420 (W210)",
  "Benefactor-Benz Vito (V447)",
  "Benefactor-Maybach Pullman",
  "Bestia GTS",
  "BF Injection",
  "Bison",
  "Blade",
  "Blista",
  "Blista Kanjo",
  "Bodhi",
  "Brawler",
  "Bravado Charger 1969",
  "Bravado Ram 1500",
  "Bravado Viper 2008",
  "Brioso R/A",
  "Buccaneer",
  "Buffalo",
  "Bullet",
  "Benefactor-MG GT",
  "Benefactor-MG SL65 (R230)",
  "Burgerfahrzeug Golf GTI Vision",
  "Bagger",
  "Bati 801",
  "Bati 801RR",
  "BF-400",
  "Blazer",
  "Blazer Lifeguard",
  "BMX",
  "Calico GTF",
  "Caracara 4x4",
  "Carbonizzare",
  "Casco",
  "Cavalcade",
  "Cheburek",
  "Cheetah",
  "Cheetah Classic",
  "Chino",
  "Clique",
  "Coil Cybertruck",
  "Coil Model S",
  "Coil Model X",
  "Coil Roadster",
  "Cognoscenti",
  "Cognoscenti 55",
  "Cognoscenti Cabrio",
  "Comet",
  "Comet S2",
  "Comet SR",
  "Contender",
  "Coquette",
  "Coquette Blackfin",
  "Coquette D10",
  "Couquette Classic",
  "Cyclone",
  "Cypher",
  "Carbon RS",
  "Chimera",
  "Cliffhanger",
  "Cruiser",
  "Declasse Corvette C7",
  "Declasse Tahoe",
  "Deveste Eight",
  "Deviant",
  "Dilettante",
  "Dinka RT-3000",
  "Dinka NSX 2017",
  "Dominator",
  "Dominator ASP",
  "Dominator GTT",
  "Dominator GTX",
  "Dominator PiBwasser",
  "Drift Yosemite",
  "Dubsta",
  "Dubsta 6x6",
  "Dubsta SG",
  "Dukes",
  "Declasse Camaro 2020",
  "Daemon",
  "Defiler",
  "Diabolus",
  "Diabolus Custom",
  "Double-T",
  "Elegy Retro Custom",
  "Elegy RH8",
  "Ellie",
  "Emperor",
  "Emperor LX-570",
  "Emperor RCF",
  "Entity XF",
  "Enus Cullinan",
  "Enus Phantom",
  "Enus Continental GT",
  "ETR-1",
  "Euros",
  "Exemplar",
  "Enduro",
  "Esskey",
  "F620",
  "Faction",
  "Felon",
  "Felon GT",
  "Feltzer",
  "Flash GT",
  "FMJ",
  "FQ 2",
  "Fugitive",
  "Furore GT",
  "Fusilade",
  "Futo",
  "Futo GTX",
  "Future Shock Issi",
  "Faggio",
  "FCR 1000",
  "FCR 1000 Custom",
  "Future Shock Deathbike",
  "Gallivanter Defender Halloween Edition",
  "Gallivanter Defender Christmas Edition",
  "Gauntlet",
  "Gauntlet Classic",
  "Gauntlet Hellfire",
  "Gauntlet Redwood",
  "GB200",
  "Glendale",
  "GP-1",
  "Granger",
  "Growler",
  "Grotti Italia (F458)",
  "GT 500",
  "Gargoyle",
  "Hermes",
  "Hotknife",
  "Huntley S",
  "Hakuchou",
  "Hakuchou Drag",
  "Hexer",
  "Imorgon",
  "Impaler",
  "Infernus",
  "Infernus Classic",
  "Ingot",
  "Issi",
  "Itali GTB",
  "Itali GTB Custom",
  "Itali GTO",
  "Innovation",
  "Jackal",
  "JB 700",
  "Jester",
  "Jester (Racecar)",
  "Jester Classic",
  "Jester RR",
  "Journey",
  "Jugular",
  "Kamacho",
  "Khamelion",
  "Komoda",
  "Krieger",
  "Karin Land Cruiser 200",
  "Karin Mark 2",
  "Karin Supra A80",
  "Karin Tundra 2021",
  "Lampadati Giulia GTA",
  "Landstalker",
  "Lynx",
  "Lectro",
  "Mamba",
  "Massacro",
  "Monroe",
  "Moonbeam",
  "Manchez",
  "Nebula Turbo",
  "Neon",
  "Nero",
  "Nero Custom",
  "Nightshade",
  "Novak",
  "Nemesis",
  "Nightblade",
  "Oracle",
  "Osiris",
  "Obey A8",
  "Obey R8",
  "Obey RS6",
  "Obey RS7",
  "Ocelot Victor",
  "Ocelot F-Type R",
  "Obey A6",
  "Obey Q8",
  "Ocelot Victor",
  "Ocelot Vanquish Zagto SB",
  "Panto",
  "Paragon R",
  "Pariah",
  "Patriot",
  "Patriot Stretch",
  "Pegassi Huayra BC",
  "Pegassi Performante (LP640)",
  "Penetrator",
  "Penumbra",
  "Peyote Gasser",
  "Pfister 811",
  "Pfister Panamera",
  "Pfister Taycan",
  "Pfister 918 Spyder",
  "Pheonix",
  "Picador",
  "Prairie",
  "Premier",
  "Previon",
  "Progen 675 LT",
  "PCJ-600",
  "Raiden",
  "Rancher XL",
  "Rapid GT",
  "Raptor",
  "Rat-Loader",
  "Rat-Truck",
  "RE-7B",
  "Reaper",
  "Rebel",
  "Rebla GTS",
  "Regina",
  "Remus",
  "Revolter",
  "Rhapsody",
  "Riata",
  "Rocoto",
  "Ruiner",
  "Rumpo",
  "Ruston",
  "Rusty Rebel",
  "Rat Bike",
  "Ruffian",
  "Sabre Turbo",
  "Sandking SWB",
  "Sandking XL",
  "SC-1",
  "Schafter",
  "Schafter LWB",
  "Schafter LWB (Armored)",
  "Schafter V12",
  "Schlagen GT",
  "Schwarzer",
  "Seminole",
  "Sentinel Classic",
  "Sentinel XS",
  "Serrano",
  "Seven-70",
  "Shelby GT500",
  "Slam Van",
  "Slamvan Custom",
  "Specter",
  "Stafford",
  "Stallion",
  "Stinger",
  "Stinger GT",
  "Stirling GT",
  "Streiter",
  "Stretch",
  "Sultan",
  "Sultan Classic",
  "Sultan RS",
  "Sultan RS Classic",
  "Super Diamond",
  "Surano",
  "Surge",
  "Swinger",
  "Sanchez",
  "Sanctus",
  "Shotaro",
  "Sovereign",
  "Street Blazer",
  "Stryder",
  "T-20",
  "Tailgater",
  "Tailgater S",
  "Taipan",
  "Tampa",
  "Tempesta",
  "Tezeract",
  "Thrax",
  "Tigon",
  "Torero",
  "Toros",
  "Tropos Rallye",
  "Tulip",
  "Turismo Classic",
  "Turismo R",
  "Truffade Chiron",
  "Tyrant",
  "Tyrus",
  "Thrust",
  "Tri-Cycles Race Bike",
  "Ubermacht 760 (LI)",
  "Ubermacht I8",
  "Ubermacht M3 (G80)",
  "Ubermacht M3 (E46)",
  "Ubermacht M5 (E34)",
  "Ubermacht M5 (E60)",
  "Ubermacht M8 (F91)",
  "Ubermacht X5 (E70)",
  "Ubermacht X5 (G05)",
  "Ubermacht X6-M (E71)",
  "Ubermacht X7 (G07)",
  "V-STR",
  "Vacca",
  "Vagner",
  "Vamos",
  "Vectre",
  "Velierer",
  "Vigero",
  "Virgo",
  "Virgo Classic",
  "Viseris",
  "Visione",
  "Voltic",
  "Voodoo",
  "Voodoo Custom",
  "Vader",
  "Vindicator",
  "Vortex",
  "Warrener",
  "Warrener HKR",
  "Washington",
  "Windsor",
  "Windsor Drop",
  "Whippet Race Bike",
  "Wolfsbane",
  "X80 Proto",
  "XA-21",
  "XLS",
  "XLS (Armored)",
  "Yosemite",
  "Yosemite Rancher",
  "Z-Type",
  "Zentorno",
  "Zion",
  "Zion Cabrio",
  "Zion Classic",
  "Zorrusso",
  "Zombie Chopper",
  "Dinghy",
  "Dinghy (2-Seater)",
  "Dinghy (Yacht)",
  "Jetmax",
  "Marquis",
  "SeaShark",
  "Speeder",
  "Squalo",
  "Suntrap",
  "Toro",
  "Tropic",
  "Alpha-Z1",
  "Cuban 800",
  "Dodo",
  "Duster",
  "Howard NX-25",
  "Luxor",
  "Luxor Deluxe",
  "Malard",
  "Mammatus",
  "Microlight",
  "Nimbus",
  "P-45 Nokota",
  "V-65 Molotok",
  "Velum",
  "Buzzard",
  "Frogger",
  "Maverick",
  "Sparrow",
  "SuperVolito Carbon",
  "Swift Deluxe",
  "Volatus",
  "Monowheel",
];

export const maleClothingNames = [
  "Air Bior pullover sweater",
  "black jacket with yellow trim",
  "bomber jacket with glowing elements",
  "branded insulated hoodie",
  "branded longsleeve",
  "branded T-shirt",
  "bright hoodie",
  "branded Molo T-shirt",
  "Casual neon set",
  "Casual neon torso",
  "Chanel top",
  "collection 2022 T-shirt",
  "cropp collection T-shirt",
  "denim jacket",
  "fur coat without a hood",
  "Glowing Bomber Set NEW Sample LW",
  "Grand RP collection hoodie",
  "Grand RP collection T-shirt",
  "haliky hoodie",
  "haliky T-shirt",
  "Hoodie with Balaclava Cap X Yazzy",
  "jacket with luminous trim",
  "jacket with T-shirt",
  "Lui Vi jacket",
  "Lui Vi sweatshirt",
  "Lui Vi full set",
  "Lui Vi T-shirt",
  "LM Playboy sweatshirt with luminous print",
  "LM Playboy jacket with luminous print",
  "LM Playboy T-shirt with luminous print",
  "LM Playboy full set with luminous print",
  "Lui Vi top",
  "Mikachu hoodie",
  "mix collection T-shirt",
  "Muci hoodie",
  "Muci hoodie with snake",
  "Muci Not Fake hoodie",
  "Muci sweatshirt",
  "Niki new collection hoodie",
  "Niki tech top",
  "Niki track suit top",
  "Off-White sweatshirt",
  "Philip Plein T-shirt",
  "scary turtleneck T-shirt",
  "Social Club hoodie",
  "Ston Islan Classic Sportswear",
  "summer collection T-shirt",
  "T-shirt of one-color CAP brand",
  "The West Pace jacket",
  "trendy jacket",
  "TRON full set",
  "TRON torso",
  "Tsum collection T-shirt",
  "vintage Abibas Olympic Jerseys",
  "luminous jacket with turquoise trim",
  "luminous T-shirt",
  "UP-Green Sweatshirt",
  "Wide printed football T-shirt",
  "Abibas pants",
  "Abibas sport pants",
  "Abibas sweatpants",
  "bright trousers",
  "Bior pants",
  "Grand RP collection pants",
  "Muci pants",
  "Muci trousers",
  "Casual neon pants",
  "half-glowing pants",
  "insulated personal pants",
  "Lui Vi pants",
  "luminous Fendi pants",
  "luminous Grand RP trousers",
  "LM Playboy pants with luminous print",
  "luminous trousers",
  "new fashionable joggers",
  "Niki new collection pants",
  "Niki tech fleece pants",
  "Niki track suit pants",
  "summer voyage shorts",
  "neon pants",
  "Neon Pants Set New Sample LW",
  "Shorts Lui Vi",
  "Leather gothic pants",
  "Abibas Marquee Boost Lows shoes",
  "Abibas Pro Bounce 2019 Lows shoes",
  "Abibas Pezy Boost 700 V3 Alvah shoes",
  "Abibas Pezy foam shoes",
  "Acic Gel Kayano sneakers.",
  "Ground Mordan 4 Retro Laser 30th shoes",
  "Muci branded flip-flops",
  "Mordan 1 shoes",
  "Mordan 6 shoes",
  "luminous shoes",
  "Off-White luminous Keezy Boost shoes",
  "luminous Keezy Boost shoes",
  "neon shoes",
  "Niki Groundporce One new collection shoes",
  "Niki Shox shoes",
  "Niki Uptempo shoes",
  "Niki Zoom Freak 1 Multi-Color shoes",
  "Off-White Pezy Boost shoes",
  "red sneakers",
  "RGB neon shoes",
  "Pans sneakers",
  "Pezy Boost shoes",
  "rare luminous shoes",
  "Casual neon shoes",
  "Balenciaga Track sneakers",
  "boxing gloves",
  "chain around the body accessory",
  "chain lost treasure neon accessory",
  "deer antler accessory",
  "deer antlers with a red nose accessory",
  "flying bear on the shoulder accessory",
  "gloves",
  "glowing snow glasses",
  "Grand Chain",
  "hearts Pride glasses",
  "neck scarf accessory",
  "pixel glasses",
  "Satanic Wings",
  "shiny deer antler headband accessory",
  "snowflake glasses",
  "wristband accessory",
  "alien with neon eyes mask",
  "anime mask",
  "bandana mask",
  "baseball mask",
  "Bigness mask",
  "boxing helmet",
  "carnival mask",
  "Casual neon helmet",
  "Christmas tree mask",
  "clown mask",
  "cowgirl hat",
  "Cupids crown",
  "Daft Punk mask",
  "demon mask",
  "desert scarf mask",
  "LM Playboy mask with luminous print",
  "Lui Vi desert scarf mask",
  "devil mask",
  "earphones with a heart",
  "emoji mask",
  "evil mask",
  "exotic mask",
  "fox mask",
  "gorilla mask",
  "Glowing face scarf mask",
  "handkerchief mask",
  "Jason blue mask",
  "kitsune mask",
  "luminous head bag mask",
  "Sashmello mask",
  "Munk mask",
  "monkey boss mask",
  "Nik mask",
  "owl mask",
  "panama hat",
  "penguin mask",
  "pig mask",
  "purge mask",
  "raccoon mask",
  "raptor mask",
  "raven mask",
  "Razer headphones",
  "red stocking mask",
  "reindeer mask",
  "robot human mask",
  "robot mask",
  "rooster mask",
  "samurai mask",
  "Santa Claus mask",
  "shamanic mask",
  "Saruko neon mask",
  "skeleton king mask",
  "snowboarders mask",
  "snowflake glasses",
  "snowman mask",
  "sports mask",
  "stealthy mask",
  "tied scarf mask",
  "tight mask",
  "toothy mask",
  "trending shark head hat",
  "TRON helmet",
  "TV-head mask",
  "Vasio G-Shock watch",
  "Volex watch of type *",
  "Kolex watch of type *",
  "Backpack Capsule skin",
  "Chain bag with spikes skin",
  "Classic Lui Vui backpack skin",
  "Cross backpack skin",
  "Cloud backpack skin",
  "Duffel Bag skin",
  "Gingerbread house backpack skin",
  "Grand backpack skin",
  "Gauard bag with Ladudu skin",
  "Happy bear shoulder bag skin",
  "LUV backpack with wings skin",
  "Memo Bag Ladudu skin",
  "Neon Chrome handbag skin",
  "Backpack with piggy keychain skin",
  "Skeleton cheetah plush backpack skin",
  "Scary chicken backpack skin",
  "SSC Kit Bag skin",
];

export const femaleClothingNames = [
  "bandana top",
  "faution top",
  "collection 5 top",
  "corset top",
  "day dress",
  "dress",
  "jumpsuit",
  "long brand T-shirt",
  "low dress",
  "pullover with long sleeve",
  "short pullover",
  "stylish suit",
  "summer bra",
  "top 2 outerwear",
  "top with chains",
  "Watch Me sweater",
  "winter collection dress",
  "Abibas leggings",
  "Abibas pants",
  "jeans",
  "skirt with tights",
  "Muci shorts",
  "tall boots",
  "luminous shoes",
  "navel piercing accessory",
  "rabbit ears",
  "Volex watch of type *",
  "Kolex watch of type *",
];

// Helper function to sort arrays alphabetically
const sortArray = (arr: string[]): string[] =>
  [...arr].sort((a, b) => a.localeCompare(b));

// OtherForm data
export const resourceTypes = sortArray([
  "Copper",
  "Emeralds",
  "Rubies",
  "Diamonds",
  "Timber",
  "Snow",
  "Scrap metal",
  "Top quality metal",
  "Threads",
  "Solar panels",
  "Fuel for resource extraction",
]);

export const containerTypes = sortArray([
  "Valuable container",
  "Desert scarf mask container",
  "Biker container",
  "Brand T-shirts 2 container",
  "Trucker container",
  "Racer container",
  "Grand racers container",
  "Ingrand container",
  "Progen container",
  "Maserati container",
  "Benefactor container",
  "Gardener container",
  "Rare love container",
  "Regular love container",
  "Renault container",
  "Resources container",
  "Diver container",
  "Organization container",
  "Sphere of influence container",
  "Wheels 1 container",
  "Wheels 2 container",
  "Wheels 3 container",
  "Old autumn gold container",
  "Old summer gold container",
  "Old winter gold container",
  "School container",
  "Arena container",
  "Daily container",
  "Halloween container",
  "Womens gift container of type 1",
  "Womens gift container of type 2",
  "Mens gift container of type 1",
  "Mens gift container of type 2",
  "Blue womens top container of type 4",
  "Black womens top container of type 4",
  "Benefactor E500 (W124) container",
  "Daily study of the organization container",
  "Captured caravans container",
  "Delivered caravans container",
  "Valentine 2025 container",
  "New years gift",
  "A Little gift",
  "A Big gift",
  "Drawing",
  "Dirty Statue",
  "Purified Statue",
]);

export const itemTypesByCategory: Record<string, string[]> = {
  "Automatic tools": sortArray([
    "automatic drill",
    "automatic sawmill",
    "automatic rod",
    "automatic oil well",
    "automatic watering can",
  ]),
  Inventory: sortArray([
    "high quality inventory",
    "medium quality inventory",
    "low quality inventory",
    "max quality inventory",
  ]),
  "Backpack skins": sortArray(["backpack skin"]),
  Batteries: sortArray(["battery"]),
  "Pet items": sortArray(["pet food", "Leash"]),
  Canisters: sortArray([
    "premium fuel canister",
    "fuel canister",
    "fuel for resource extraction",
  ]),
  Chargers: sortArray(["charger"]),
  "Christmas resources": sortArray([
    "Christmas key",
    "Christmas copper",
    "Christmas timber",
    "Christmas perch",
    "Christmas seed",
    "Christmas lollipop",
  ]),
  Containers: sortArray(containerTypes),
  Resources: sortArray(resourceTypes),
  Dice: sortArray(["dice"]),
  Fish: sortArray(["perch", "carp", "salmon", "trout"]),
  "Fishing rods": sortArray(["fishing rod"]),
  "Fruits and vegetables": sortArray([
    "mandarin",
    "pumpkin",
    "strawberry",
    "pineapple",
    "cabbage",
  ]),
  Fireworks: sortArray(["firework"]),
  Hookahs: sortArray(["hookah"]),
  Juices: sortArray([
    "attack juice",
    "protection juice",
    "endurance juice",
    "riding juice",
    "power juice",
    "immunity juice",
    "juice on becoming an animal",
    "juice for double the payment",
    "fast running juice",
  ]),
  Letters: sortArray([
    "letter G",
    "letter R",
    "letter A",
    "letter N",
    "letter D",
  ]),
  "License plates": sortArray(["license plate"]),
  "Lottery tickets": sortArray([
    "regular lottery ticket",
    "rare lottery ticket",
    "flame and water lottery ticket",
  ]),
  "Luminous wheels": sortArray(["luminous wheels"]),
  Masks: sortArray(["mask"]),
  Milk: sortArray(["milk"]),
  "Mining resources": sortArray([
    "copper",
    "emerald",
    "ruby",
    "diamond",
    "scrap metal",
    "top quality metal",
  ]),
  Mushrooms: sortArray(["mushroom"]),
  "Paint cans": sortArray(["paint can"]),
  Pearls: sortArray(["pearl"]),
  Pickaxes: sortArray(["pickaxe"]),
  Prime: sortArray(["Prime", "Prime Platinum"]),
  "Repair kits": sortArray(["repair kit"]),
  "Resource barrels": sortArray([
    "solar barrel",
    "gasoline barrel",
    "kerosene barrel",
  ]),
  Seeds: sortArray([
    "pineapple seed",
    "cabbage seed",
    "pumpkin seed",
    "mandarin seed",
    "mushroom seed",
  ]),
  Snow: sortArray(["snow"]),
  "Solar panels": sortArray(["solar panel"]),
  "SIM cards": sortArray(["SIM card"]),
  Threads: sortArray(["thread"]),
  Tickets: sortArray([
    "Grand ticket",
    "Cayo Perico ticket",
    "Car ticket",
    "Secret ticket fragment",
    "Secret ticket",
    "Resource Miners ticket",
  ]),
  Timber: sortArray(["timber"]),
  Tokens: sortArray(["token"]),
  "Tonic treats": sortArray(["tonic treat"]),
  "Video cards": sortArray(["video card"]),
  Wires: sortArray(["wire"]),
  "Tuning parts": sortArray(["tuning parts"]),
};

export const partyLocations = [
  "Houses/apartment",
  "beach",
  "yacht",
  "Bahama Mamas Bar",
  "Tequi-la-la Bar",
  "Stadium",
  "Diamond Resort Bar (Casino Restaurant)",
  "Vanilla Unicorn Bar",
  "Hotel Spa Bar",
  "Cayo Perico Island",
  "Vinewood Hills",
  "Rockford Hills",
  "Richman",
  "Sandy Shores",
  "Paleto Bay",
  "Chumash",
  "Del Perro Pier",
  "Del Perro Beach",
  "Raton Canyon",
  "Hotel",
  "School",
  "SAHP",
  "FIB",
  "Hospital",
  "Capitol",
  "Fire Station",
  "Auto Fair",
  "Church",
  "Stock Exchange",
  "Lifeinvader",
  "Postal",
  "airport",
  "autosalon",
  "beach market",
  "ghetto",
  "post office",
  "train station",
  "the city",
];

export const partyTypes = [
  "Party",
  "Pool party",
  "Wedding",
  "Car meet",
  "Exclusive car meet",
];

export const serviceTypes = [
  "Looking for a lawyer",
  "Looking for a personal driver",
  "Looking for a professional dancer",
  "Looking for a professional singer",
  "Looking for a DJ",
  "Wedding at Church",
  "Looking to play poker",
];

export const itemCategories = [
  "Automatic tools",
  "Backpack skins",
  "Batteries",
  "Canisters",
  "Chargers",
  "Christmas resources",
  "Containers",
  "Dice",
  "Fish",
  "Fireworks",
  "Fishing rods",
  "Fruits and vegetables",
  "Fuel for resource extraction",
  "Hookahs",
  "Inventory",
  "Juices",
  "Leash",
  "Letters",
  "License plates",
  "Lottery tickets",
  "Luminous wheels",
  "Masks",
  "Milk",
  "Mining resources",
  "Mushrooms",
  "Paint cans",
  "Pearls",
  "Pet food",
  "Pet items",
  "Pickaxes",
  "Prime",
  "Repair kits",
  "Resource barrels",
  "Resource Miners tickets",
  "Resources",
  "Scrap metal",
  "Seeds",
  "SIM cards",
  "Snow",
  "Solar panels",
  "Threads",
  "Tickets",
  "Timber",
  "Tokens",
  "Tonic treats",
  "Top quality metal",
  "Tuning parts",
  "Video cards",
  "Wires",
].sort((a, b) => a.localeCompare(b));

export const petTypes = ["Shoulder pets", "Caged pets"];

export const shoulderPets = [
  "six tailed fox on shoulder pet",
  "hamster on shoulder pet",
  "strong chicken on shoulder pet",
  "owl on shoulder pet",
  "flying bear on shoulder pet",
  "toothless dragon on shoulder pet",
  "leon brawl on shoulder pet",
  "lovely bird egg on shoulder pet",
  "Mr. Robot friend on shoulder pet",
  "el primo corazon brawl on shoulder pet",
  "black voron on shoulder pet",
];

export const cagedPets = [
  "cage with a Border Collie",
  "cage with a Cat",
  "cage with a Cougar",
  "cage with a Cyberdog",
  "cage with a Husky",
  "cage with a Panther",
  "cage with a Pig",
  "cage with a Poodle",
  "cage with a Monkey",
  "cage with a Pug",
  "cage with a Christmas Elf",
  "cage with a Santa Claus",
  "cage with a Fancy bear",
  "cage with a Cute Hippo",
  "cage with a New years Husky",
  "cage with a Rabbit",
  "cage with a Rat",
  "cage with a Retriever",
  "cage with a Robobeast",
  "cage with a Rooster",
  "cage with a Puma",
  "cage with a Rottweiler",
  "cage with a Westie",
  "cage with a Kitty Bunny",
  "cage with a Duckling",
  "cage with a Panda",
  "cage with a Lion Cub",
  "cage with a Mini Robot",
];

export const clothingTypes = [
  "Shirts for men",
  "Shoes for women",
  "TRON full set",
  "TRON helmet",
  "Lui Vi full set",
  "Clothing for women",
  "Clothing for men",
  "Desert scarf mask",
  "Luminous clothes",
  "Grand RP collection",
];

export const gamblingTypes = ["Dice", "Poker", "Lottery"];

export const allianceTypes = [
  "Looking for an alliance",
  "Family alliance",
  "Business alliance",
];
